export const FETCHING_API = 'FETCHING_API';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';

export const FILTERING_API = 'FILTERING_API';
export const FILTER_API_SUCCESS = 'FILTER_API_SUCCESS';
export const FILTER_API_FAILURE = 'FILTER_API_FAILURE';

export const ADDING_API = 'ADDING_API';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAILURE = 'ADD_FAILURE';

export const RECOMMENDATIONS_API = 'RECOMMENDATIONS_API';
export const RECOMMENDATIONS_SUCCESS = 'RECOMMENDATIONS_SUCCESS';
export const RECOMMENDATIONS_FAILURE = 'RECOMMENDATIONS_FAILURE';